### ISSUE TITLE
Python version 3.5 or 3.6

### ISSUE THREAD

**Issue by Kata5** [soltanianzadeh/STNeuroNet#10]
There are some doubts about Python version:
On https://github.com/soltanianzadeh/STNeuroNet/wiki/Installation-on-Windows-for-an-all-Python-software Python 3.6 is recommended, while on
https://github.com/soltanianzadeh/STNeuroNet  Anaconda with Python 3.5  is recommeded

**Comment by soltanianzadeh** [comment]
Sorry for the confusion. It should be python 3.5. I have edited the Wiki page.
