### ISSUE TITLE
Errpr with wkspintrospect.dll

### ISSUE THREAD

**Issue by Kata5** [soltanianzadeh/STNeuroNet#11]
When I try to run demo_inference.py  I get the following error message: (MAtlab 2017b is installed with the proper Matlab RunTime)

Can't load 'C:\Program Files\MATLAB\R2017b\bin\win64\wkspintrospect.dll':
Error in ctfroot (line 15)
Error in checkRequiredMCRProducts (line 14)
Traceback (most recent call last):
  File "demo_inference.py", line 27, in <module>
    matlabLib = STNeuroNetPkg.initialize()
  File "C:\Users\ocsai.katalin\AppData\Local\Continuum\anaconda3\envs\stneuronet\lib\site-packages\STNeuroNetPkg\__init__.py", line 301, in initialize
    return _pir.initialize_package()
  File "C:\Users\ocsai.katalin\AppData\Local\Continuum\anaconda3\envs\stneuronet\lib\site-packages\STNeuroNetPkg\__init__.py", line 249, in initialize_package
    package_handle.initialize()
  File "C:\Program Files\MATLAB\R2017b\toolbox\compiler_sdk\pysdk_py\matlab_pysdk\runtime\deployablepackage.py", line 33, in initialize
    mcr_handle = self.__cppext_handle.startMatlabRuntimeInstance(self.__ctf_path)
SystemError: Can't load 'C:\Program Files\MATLAB\R2017b\bin\win64\wkspintrospect.dll'

**Comment by soltanianzadeh** [comment]
I'm guessing it might be a path issue. Make sure MATLAB and MATLAB Runtime have been added to your system path.

**Comment by mtugsbayar** [comment]
I'm having the same issue, and my path variable leads to where the wkspintrospect.dll file is. Can you look further into the issue? Thank you.

**Comment by Kata5** [comment]
@soltanianzadeh  I have checked everything, the path is correct. Moreover I have uninstalled and reinstalled Anacoda but the error is still the same. If anyone can help me that would be really appreciated. The paper seems to be great, it  would be very nice if I could use it on our own data.

**Comment by maraid** [comment]
I ran into the same problem. Can you look into it please?

**Comment by Kata5** [comment]
@soltanianzadeh  Could you please provide me information about the version of Windows you use? Many thanks in advance!

**Comment by soltanianzadeh** [comment]
@Kata5 I have Windows 10.

@mtugsbayar @maraid I will look into it and post here when I find a solution. Meanwhile, you can use the provided [MATLAB demos](https://github.com/soltanianzadeh/STNeuroNet/wiki/Running-Trained-Networks-on-Data#matlab-demos) to run through the pipeline.

**Comment by Kata5** [comment]
@soltanianzadeh Is there any way simply to use your already trained network on new data without downloading Allen Dataset, etc? I still have the problem with wkspintrospect and if it is not necessary I would not try to run the training code from MATLAB demos so that just to have a single try on new data

**Comment by Kata5** [comment]
@soltanianzadeh, I would also be happy if I could run just a very short demo on _any_ data without editing demo_config_empty.ini.
Or in last case: it would be also enough if you could provide me only a movie in which STDneuroNet finds Ca sources on any data, just to have a short illustration how it works. (could not find in supplementary)

If anyone can screencast and provide me a movie that would me much appreciated. I would just like to decide whether it is worth to try to work with this repo or not.
Thank you very much in advance!

**Comment by soltanianzadeh** [comment]
@Kata5 @mtugsbayar @maraid  I think I have figured out what the problem is. The wkspintrospect.dll error could have been caused by h5py, which gets called when importing niftynet.  To verify this is the case for you, try the following:
```
import STNeuroNetPkg
import matlab
matlabLib = STNeuroNetPkg.initialize()
import h5py
```

If you get the error ` AttributeError: type object 'h5py.h5r.Reference' has no attribute
'__reduce_cython__'`, then h5py is the source of error. To solve this, make sure you only have the latest version of h5py installed. Uninstall h5py and then reinstall with `pip install h5py`.

Hope this solves the issue!

**Comment by soltanianzadeh** [comment]
@Kata5 I have uploaded a short tutorial [here](https://github.com/soltanianzadeh/STNeuroNet/tree/master/wiki). Hope it helps.

**Comment by mtugsbayar** [comment]
@soltanianzadeh Thanks for the response. It seems like a problem with h5py, but I'm getting a different error:

  File "stdin", line 1, in module
  File "C:\Users\mtugsbayar\AppData\Local\Continuum\anaconda3\envs\stneuronet\lib\site-packages\h5py\__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py\h5r.pxd", line 21, in init h5py._conv
  File "h5py\_objects.pxd", line 12, in init h5py.h5r
  File "h5py\_objects.pyx", line 1, in init h5py._objects
ImportError: DLL load failed: The specified procedure could not be found.

Uninstalling and installing the latest version of h5py does not resolve the issue

**Comment by soltanianzadeh** [comment]
@mtugsbayar can you report the output of `conda list` ?

**Comment by mtugsbayar** [comment]
Sure. Conda list for the environment I'm using (the environment was generated with the environment.yml file provided):

# packages in environment at C:\Users\mtugsbayar\AppData\Local\Continuum\anaconda3\envs\stneuronet:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py36_0
asn1crypto                0.24.0                   py36_0
astroid                   2.2.5                    py36_0
attrs                     19.1.0                   py36_1
babel                     2.7.0                      py_0
backcall                  0.1.0                    py36_0
blas                      1.0                         mkl
bleach                    1.5.0                    pypi_0    pypi
ca-certificates           2019.5.15                     0
certifi                   2019.6.16                py36_0
cffi                      1.12.3           py36h7a1dbc1_0
chardet                   3.0.4                    py36_1
cloudpickle               1.2.1                      py_0
colorama                  0.4.1                    py36_0
configparser              3.7.4                    pypi_0    pypi
cryptography              2.7              py36h7a1dbc1_0
cycler                    0.10.0           py36h009560c_0
cython                    0.29.12          py36ha925a31_0
decorator                 4.4.0                    py36_1
defusedxml                0.6.0                      py_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.3                      py36_0
enum34                    1.1.6                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1
h5py                      2.9.0            py36h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
html5lib                  0.9999999                pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py36_0
imagesize                 1.1.0                    py36_0
intel-openmp              2019.4                      245
ipykernel                 5.1.1            py36h39e3cac_0
ipython                   7.6.1            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
isort                     4.3.21                   py36_0
jedi                      0.13.3                   py36_0
jinja2                    2.10.1                   py36_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.0.1                    py36_0
jupyter_client            5.3.1                      py_0
jupyter_core              4.5.0                      py_0
keyring                   18.0.0                   py36_0
kiwisolver                1.1.0            py36ha925a31_0
lazy-object-proxy         1.4.1            py36he774522_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
markdown                  3.1.1                    pypi_0    pypi
markupsafe                1.1.1            py36he774522_0
matlab                    0.1                      pypi_0    pypi
matlabruntimeforpython    R2017b                   pypi_0    pypi
matplotlib                3.1.0            py36hc8f65d3_0
mccabe                    0.6.1                    py36_1
mistune                   0.8.4            py36he774522_0
mkl                       2019.4                      245
mkl_fft                   1.0.12           py36h14836fe_0
mkl_random                1.0.2            py36h343c172_0
nbconvert                 5.5.0                      py_0
nbformat                  4.4.0            py36h3a5bc1b_0
nibabel                   2.4.1                    pypi_0    pypi
niftynet                  0.2.0.post1              pypi_0    pypi
numpy                     1.16.4                   pypi_0    pypi
numpy-base                1.16.4           py36hc3f5095_0
numpydoc                  0.9.1                      py_0
openssl                   1.1.1c               he774522_1
packaging                 19.0                     py36_0
pandas                    0.24.2                   pypi_0    pypi
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py36_1
parso                     0.5.0                      py_0
pathlib                   1.0.1                    py36_1
pickleshare               0.7.5                    py36_0
pillow                    6.1.0                    pypi_0    pypi
pip                       19.1.1                   py36_0
prompt_toolkit            2.0.9                    py36_0
protobuf                  3.9.0                    pypi_0    pypi
psutil                    5.6.3            py36he774522_0
pycodestyle               2.5.0                    py36_0
pycparser                 2.19                     py36_0
pyflakes                  2.1.1                    py36_0
pygments                  2.4.2                      py_0
pylint                    2.3.1                    py36_0
pyopenssl                 19.0.0                   py36_0
pyparsing                 2.4.0                      py_0
pyqt                      5.9.2            py36h6538335_2
pyreadline                2.1                      py36_1
pyrsistent                0.14.11          py36he774522_0
pysocks                   1.7.0                    py36_0
python                    3.6.8                h9f7ef89_7
python-dateutil           2.8.0                    py36_0
pytz                      2019.1                     py_0
pywin32                   223              py36hfa6e2cd_1
pyzmq                     18.0.0           py36ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.5.7                    py36_1
qtconsole                 4.5.1                      py_0
qtpy                      1.8.0                      py_0
requests                  2.22.0                   py36_0
rope                      0.14.0                     py_0
scipy                     1.2.1            py36h29ff71c_0
setuptools                41.0.1                   pypi_0    pypi
sip                       4.19.8           py36h6538335_0
six                       1.12.0                   pypi_0    pypi
snowballstemmer           1.9.0                      py_0
sphinx                    2.1.2                      py_0
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
spyder                    3.3.6                    py36_0
spyder-kernels            0.5.1                    py36_0
sqlite                    3.29.0               he774522_0
tensorflow-gpu            1.4.0                    pypi_0    pypi
tensorflow-tensorboard    0.4.0                    pypi_0    pypi
testpath                  0.4.2                    py36_0
tornado                   6.0.3            py36he774522_0
traitlets                 4.3.2            py36h096827d_0
typed-ast                 1.3.4            py36he774522_0
urllib3                   1.24.2                   py36_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1                    py36_1
werkzeug                  0.15.5                   pypi_0    pypi
wheel                     0.33.4                   pypi_0    pypi
win_inet_pton             1.1.0                    py36_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.11.2           py36he774522_0
zeromq                    4.3.1                h33f27b4_3
zlib                      1.2.11               h62dcd97_3

**Comment by soltanianzadeh** [comment]
@mtugsbayar it seems that h5py was installed through conda, not pip. Try `cond uninstall h5py` and then `pip install h5py`

**Comment by mtugsbayar** [comment]
@soltanianzadeh I did download h5py through pip, but I've abandoned the windows install and I'm currently doing it on linux, since that seems to work smoother for me. Thank you!

**Comment by Daniel0520** [comment]
> 
> 
> @Kata5 @mtugsbayar @maraid I think I have figured out what the problem is. The wkspintrospect.dll error could have been caused by h5py, which gets called when importing niftynet. To verify this is the case for you, try the following:
> 
> ```
> import STNeuroNetPkg
> import matlab
> matlabLib = STNeuroNetPkg.initialize()
> import h5py
> ```
> 
> If you get the error ` AttributeError: type object 'h5py.h5r.Reference' has no attribute '__reduce_cython__'`, then h5py is the source of error. To solve this, make sure you only have the latest version of h5py installed. Uninstall h5py and then reinstall with `pip install h5py`.
> 
> Hope this solves the issue!

@soltanianzadeh , thank you for the response. I've just tried these code lines but I got exactly the same error as before

(stneuronet3_5) C:\STNeuroNet\STNeuroNet>python demo_inference.py
Can't load 'C:\Program Files\MATLAB\MATLAB Runtime\v93\bin\win64\wkspintrospect.dll': not foundˇ.


Error in ctfroot (line 15)


Error in checkRequiredMCRProducts (line 14)

Traceback (most recent call last):
  File "demo_inference.py", line 26, in <module>
    matlabLib = STNeuroNetPkg.initialize()
  File "C:\Users\xx\AppData\Local\Continuum\anaconda3\envs\stneuronet3_5\lib\site-packages\STNeuroNetPkg\__init__.py", line 301, in initialize
    return _pir.initialize_package()
  File "C:\Users\xx\AppData\Local\Continuum\anaconda3\envs\stneuronet3_5\lib\site-packages\STNeuroNetPkg\__init__.py", line 249, in initialize_package
    package_handle.initialize()
  File "C:\Program Files\MATLAB\MATLAB Runtime\v93\toolbox\compiler_sdk\pysdk_py\matlab_pysdk\runtime\deployablepackage.py", line 33, in initialize
    mcr_handle = self.__cppext_handle.startMatlabRuntimeInstance(self.__ctf_path)
SystemError: Can't load 'C:\Program Files\MATLAB\MATLAB Runtime\v93\bin\win64\wkspintrospect.dll': not found.

**Comment by Daniel0520** [comment]
Would it be possible to reopen this issue?

**Comment by soltanianzadeh** [comment]
@Daniel0520 can you report the output of conda list? Cython, h5py, lxml, python, and scipy can run into compatibility issues resulting in this error.

**Comment by Daniel0520** [comment]
Sure, I got the same result as Kata5.

**Comment by soltanianzadeh** [comment]
@Daniel0520 Try installing the following version of packages:
cython    0.24.1
h5py       2.7.0
scipy       1.3.1
lxml         4.2.5
python    3.5
