### ISSUE TITLE
Error after changing training videos

### ISSUE THREAD

**Issue by mtugsbayar** [soltanianzadeh/STNeuroNet#14]
Hello,

I'm encountering a bug while running the net segment. Previously, I ran the training with a different set of videos and encountered no problems. However, during this run, demo_train is writing ",501704220" to filename_not_contains for some reason. That file does not exist anymore in the dataset directory and I haven't included it in the list of videos to train.

NiftyNet version 0.2.0.post1
usage:  [-h] [--csv_file] [--path_to_search] [--filename_contains]
        [--filename_not_contains] [--interp_order {0,1,2,3}] [--pixdim PIXDIM]
        [--axcodes AXCODES] [--spatial_window_size SPATIAL_WINDOW_SIZE]
: error: argument --filename_not_contains: list of strings expected, for each list element the allowedcharacters: [ a-zA-Z0-9], but received ,501704220
(stneuronet) [mtugsbayar@firefly STNeuroNet]$ python demo_train.py
/home/mtugsbayar/anaconda3/envs/stneuronet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/mtugsbayar/anaconda3/envs/stneuronet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/mtugsbayar/anaconda3/envs/stneuronet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/mtugsbayar/anaconda3/envs/stneuronet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/mtugsbayar/anaconda3/envs/stneuronet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/mtugsbayar/anaconda3/envs/stneuronet/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:476: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/mtugsbayar/anaconda3/envs/stneuronet/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
NiftyNet version 0.2.0.post1
usage:  [-h] [--csv_file] [--path_to_search] [--filename_contains]
        [--filename_not_contains] [--interp_order {0,1,2,3}] [--pixdim PIXDIM]
        [--axcodes AXCODES] [--spatial_window_size SPATIAL_WINDOW_SIZE]
: error: argument --filename_not_contains: list of strings expected, for each list element the allowedcharacters: [ a-zA-Z0-9], but received ,501704220

**Comment by soltanianzadeh** [comment]
The error is because the string name in file_not_contains starts with comma. Please revise line 150 in `demo_train.py` to be `temp = mystr[:-1] `.

Let me know if this solved the error.

**Comment by mtugsbayar** [comment]
It works now! Thank you!
