### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by oregonGCAMP** [soltanianzadeh/STNeuroNet#15]
Hello,

I am running python version 3.7.3 on a Windows machine and I was able to complete the first step of the install "conda env create -f environment.yml -n stneuronet". I suspect it is because I am not running python 3.5. Below is the prompt text..

Thanks,

Andrei

(base) c:\Users\sdrulla\STNeuroNet\STNeuroNet-master>conda env create -f environment.yml -n stneuronet
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining wheel:   2%|█▍                                                                       | 3/147 [00:00<?, ?it/-
Examining certifi:   3%|██▏                                                            | 5/147 [00:18<08:39,  3.66s/i-
Comparing specs that have this dependency:  38%|███████████████▍                         | 3/8 [00:32<00:53, 10.75s/i| \
Comparing specs that have this dependency:  50%|████████████████████▌                    | 4/8 [00:36<00:36,  9.14s/it]\
Examining setuptools:  79%|█████████████████████████████████████████████▊            | 116/147 [01:47<04:27,  8.62s/i| /Examining python:  99%|█████████████████████████████████████████████████████████████▏| 145/147 [02:00<00:08,  4.34s/i\ -
failed
                                                                                                                       |
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package certifi conflicts for:
h5py -> python[version='>=3.5,<3.6.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2017.4.17']
pathlib -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2017.4.17']
matplotlib -> setuptools -> certifi[version='>=2016.09']
scipy -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2017.4.17']
cython -> python[version='>=3.6,<3.7.0a0'] -> pip -> requests -> certifi[version='>=2017.4.17']
python=3.5 -> pip -> setuptools -> certifi[version='>=2016.09|>=2017.4.17']
cython -> setuptools -> certifi[version='>=2016.09']
matplotlib -> python[version='>=3.6,<3.7.0a0'] -> pip -> requests -> certifi[version='>=2017.4.17']
numpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2017.4.17']
Package msgpack-python conflicts for:
spyder -> python[version='>=3.6,<3.7.0a0'] -> pip -> cachecontrol -> msgpack-python
numpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> cachecontrol -> msgpack-python
h5py -> python[version='>=3.5,<3.6.0a0'] -> pip -> cachecontrol -> msgpack-python
scipy -> python[version='>=3.6,<3.7.0a0'] -> pip -> cachecontrol -> msgpack-python
cython -> python[version='>=3.6,<3.7.0a0'] -> pip -> cachecontrol -> msgpack-python
matplotlib -> python[version='>=3.6,<3.7.0a0'] -> pip -> cachecontrol -> msgpack-python
pathlib -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> msgpack-python
python=3.5 -> pip -> cachecontrol -> msgpack-python
Package wincertstore conflicts for:
python=3.5 -> pip -> setuptools -> wincertstore[version='>=0.2']
pathlib -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools -> wincertstore[version='>=0.2']
cython -> setuptools -> wincertstore[version='>=0.2']
scipy -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> wincertstore[version='>=0.2']
h5py -> python[version='>=3.5,<3.6.0a0'] -> pip -> setuptools -> wincertstore[version='>=0.2']
matplotlib -> setuptools -> wincertstore[version='>=0.2']
numpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> wincertstore[version='>=0.2']
spyder -> pyflakes -> setuptools -> wincertstore[version='>=0.2']
Package wheel conflicts for:
cython -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
pathlib -> python[version='>=2.7,<2.8.0a0'] -> pip -> wheel
spyder -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
python=3.5 -> pip -> wheel
matplotlib -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
numpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
scipy -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
h5py -> python[version='>=3.5,<3.6.0a0'] -> pip -> wheel
Package pip conflicts for:
pathlib -> python[version='>=2.7,<2.8.0a0'] -> pip
spyder -> python[version='>=3.6,<3.7.0a0'] -> pip
numpy -> python[version='>=3.6,<3.7.0a0'] -> pip
cython -> python[version='>=3.6,<3.7.0a0'] -> pip
matplotlib -> python[version='>=3.6,<3.7.0a0'] -> pip
python=3.5 -> pip
scipy -> python[version='>=3.6,<3.7.0a0'] -> pip
h5py -> python[version='>=3.5,<3.6.0a0'] -> pip
Package python conflicts for:
spyder -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
scipy -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
matplotlib -> pyparsing -> python
python=3.5
cython -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
pathlib -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
h5py -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
numpy -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
Package ca-certificates conflicts for:
matplotlib -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
pathlib -> python[version='>=2.7,<2.8.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
python=3.5 -> pip -> requests -> urllib3[version='>=1.21.1,<1.24'] -> cryptography[version='>=1.3.4'] -> openssl=1.0 -> ca-certificates
numpy -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
cython -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
scipy -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
h5py -> python[version='>=3.5,<3.6.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
spyder -> pyflakes -> setuptools -> ca-certificates
Package setuptools conflicts for:
spyder -> pyflakes -> setuptools
python=3.5 -> pip -> setuptools
matplotlib -> setuptools
scipy -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools
cython -> setuptools
numpy -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools
h5py -> python[version='>=3.5,<3.6.0a0'] -> pip -> setuptools
pathlib -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools
Package python-dateutil conflicts for:
matplotlib -> python-dateutil
Package ipython conflicts for:
spyder -> nbconvert -> jupyter_client[version='>=4.2'] -> ipython[version='>=4.0|>=4.0.0|>=5.0']
Package ipython_genutils conflicts for:
spyder -> sphinx -> ipython_genutils

**Comment by soltanianzadeh** [comment]
Dear Andrei,
You can install python 3.5 in your environment. See here for further details https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html

**Comment by oregonGCAMP** [comment]
Hi,

I continue to get the same error message when trying to run the conda env
create -f environment.yml -n stneuronet command. The error message is
pasted below. Any thoughts?

Thanks,

Andrei

[image: image.png]
