### ISSUE TITLE
MATLAB file demo_preprocess.m BUG

### ISSUE THREAD

**Issue by RenieWell** [soltanianzadeh/STNeuroNet#2]
Hello!
I am trying to follow your excellent job, but I met several problem.
I follow the step by step install guidance in the wiki, the only difference is that I use MATLAB R2018a under Ubuntu system.
The problem showed at line 18 `prepareAllen(opt)`
and turn out that `opt` didn't contain the right H5 file path.
After I fixed this, I found that the code in `prepareAllen.m` Line 17 have a bug, it returned `>> infoVid.Datasets.Dataspace.Size;
Expected one output from a curly brace or dot indexing expression, but there were
5 results.`
I have no idea how to fix this one, could you please give me some advice?

**Comment by soltanianzadeh** [comment]
Dear @RenieWell, thanks for reporting the bug in the code. I have updated the codes to fix the issue related to the data path.

I don't have access to a Ubuntu system at the time, but I might be able to help. I just want to make sure that you running the code on the Allen Brain Observatory dataset. If so, can you tell me what the output of infoVid.Datasets.Dataspace.Size is? Thanks.

**Comment by RenieWell** [comment]
Thanks for reply so quick!
After your kindly repair, I find out the problem.
 The file I download from Allen Brain Observatory dataset is named as '501559087.nwb', which also a h5 file according to their website.
But it seems that the right h5 file should have a name like './Dataset/ABO/ophys_experiment_501559087_concat_31Hz_0.h5'.
Can you give me a example about how to download the right h5 file?

**Comment by soltanianzadeh** [comment]
@RenieWell The .nwb files contain summary data they've extracted from the two-photon recordings, for example, traces and masks of neurons. These do not have the raw two-photon videos.

To access the raw recordings, please take a look at the image below, which is a screenshot from Allen's S3 bucket. It seems that they've changed the name of their files from, for example, ophys_experiment_501559087_concat_31Hz_0.h5 to ophys_experiment_501559087.h5. So I've updated the code to take this into account.

![image](https://user-images.githubusercontent.com/31009809/56387034-47230200-61f1-11e9-8eff-3af0a5abdbe3.png)

**Comment by RenieWell** [comment]
Thanks a lot! 
Problems solved.
