### ISSUE TITLE
Availability of ABO dataset

### ISSUE THREAD

**Issue by hluetck** [soltanianzadeh/STNeuroNet#5]
Hello,

would it be possible to make the ABO dataset used in the paper and the demo scripts available for download? It seems the raw movies are not easily obtainable from the Allen institute.

Thanks. Henry

**Comment by soltanianzadeh** [comment]
Hello Henry. Unfortunately I cannot redistribute data from the Allen Institute.  I can help you download the data from their S3 bucket. 
Have you looked at https://github.com/AllenInstitute/AllenSDK/wiki/Use-the-Allen-Brain-Observatory-–-Visual-Coding-on-AWS ? Also, you may find this issue https://github.com/soltanianzadeh/STNeuroNet/issues/2#issuecomment-484665339 helpful.

**Comment by hluetck** [comment]
OK, thanks for your reply.
