### ISSUE TITLE
prerequisites for STNeuroNet

### ISSUE THREAD

**Issue by symonova** [soltanianzadeh/STNeuroNet#6]
It would be great if you can post hardware and software prerequisites for the STNeuroNet. For example, tensorflow 1.4 requires CUDA 8.0 and cudnn libraries installed. It would be great if you can provide the links from where software prerequisites can be installed.

**Comment by soltanianzadeh** [comment]
Dear @symonova, it is best to have a GPU with large memory (for example 12GB as in Titan Xp or 1080Ti). I also recommend minimum of 16GB of RAM for reading and preprocessing the original Allen recordings. You can find the CUDA and cuDNN in the following links:
CUDA archive: https://developer.nvidia.com/cuda-toolkit-archive
cuDNN archive: https://developer.nvidia.com/rdp/cudnn-archive

**Comment by soltanianzadeh** [comment]
Feel free to reopen the issue if needed.
