### ISSUE TITLE
Run into error No module named 'matlabruntimeforpython3_6'

### ISSUE THREAD

**Issue by Fei-Xia-oe** [soltanianzadeh/STNeuroNet#7]
After running the 
!python setup.py install
for the redistribution in Windows, and I ran
 import STNeuroNetPkg,
I got the error No module named 'matlabruntimeforpython3_6'
Does anyone have an idea how to troubleshoot this?

**Comment by soltanianzadeh** [comment]
@emilyxia Try with python 3.5

**Comment by soltanianzadeh** [comment]
Feel free to reopen the issue if needed.
